/* GLOBAL PARAMS? WHAT IS THIS>? */

EOS_Spawn = compile preprocessfilelinenumbers "eos\core\eos_launch.sqf";

MISSON_COMPLETE = 0;
SECTOR_SPAWNRADIUS = 850;
RADIOTOWER_COMSRADIUS = 2500;
MILOBJ_INFLURADIUS = 1200;
PRIOBJ_INFLURADIUS = 1200;
FOB_INFLURADIUS = 100;
